tusc_api:
  tusc_wallet_port: "5071"
  tusc_wallet_ip: "localhost"
  tusc_wallet_rpc_endpoint: "/rpc"
  tusc_wallet_rpc_version: "2.0"
  registrar_account_name: "registration-faucet"
db:
  host: "localhost"
  user: "postgres"
  password: "fakepass"
  database: "tusc-registrar"
  port: 5432
general:
  testing: False
  captcha_secret: "UNKNOWN"
  ip_request_blocking_hours: 24
  highest_block_number_handled: 8533137
  disable_recaptcha: True
  disable_ip_blocking: True
wallet:
  path: "/home/tuscy/TUSC-v2.5.2/cli_wallet"
  chain_id: "eb938e2a955e39e335120d0a99f3b9f8c04a9ed5690275ea5037d6bbadfc6cf3"
  wallet_password: "1"
  node_address: "wss://api.tusc.network:8443"